mkdir -p Apptics-SDK/1.1.8/
mkdir -p Apptics-Swift/1.1.8/
mkdir -p AppticsAnalytics/1.1.8/
mkdir -p AppticsApiTracker/1.1.8/
mkdir -p AppticsCrossPromotion/1.1.8/
mkdir -p AppticsExtension/1.1.8/
mkdir -p AppticsFeedbackKit/1.1.8/
mkdir -p AppticsFeedbackKitSwift/1.1.8/
mkdir -p AppticsInAppUpdate/1.1.8/
mkdir -p AppticsRateUs/1.1.8/
mkdir -p AppticsRemoteConfig/1.1.8/

cp Apptics-SDK.podspec Apptics-SDK/1.1.8/
cp Apptics-Swift.podspec Apptics-Swift/1.1.8/
cp AppticsAnalytics.podspec AppticsAnalytics/1.1.8/
cp AppticsApiTracker.podspec AppticsApiTracker/1.1.8/
cp AppticsCrossPromotion.podspec AppticsCrossPromotion/1.1.8/
cp AppticsExtension.podspec AppticsExtension/1.1.8/
cp AppticsFeedbackKit.podspec AppticsFeedbackKit/1.1.8/
cp AppticsFeedbackKitSwift.podspec AppticsFeedbackKitSwift/1.1.8/
cp AppticsInAppUpdate.podspec AppticsInAppUpdate/1.1.8/
cp AppticsRateUs.podspec AppticsRateUs/1.1.8/
cp AppticsRemoteConfig.podspec AppticsRemoteConfig/1.1.8/