# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/zoho/Apptics.git'
source 'https://git.csez.zohocorpin.com/zoho/zohopodspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

#source "https://github.com/CocoaPods/Specs.git"
#source "https://git.csez.zohocorpin.com/zoho/zohopodspecs.git"
target 'AppticsDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

#pod 'Apptics', '1.0.1' , :source => 'https://github.com/zoho/Apptics.git'
#pod 'Apptics-SDK', '1.0.1' , :source => 'https://git.csez.zohocorpin.com/zoho/zohopodspecs.git'
pod 'Apptics-Swift', '1.0.1' , :source => 'https://git.csez.zohocorpin.com/zoho/zohopodspecs.git' #:source => 'https://github.com/CocoaPods/Specs.git'
#
#pod 'AppticsFeedbackKit', '1.0.1'
#pod 'AppticsRemoteConfig', '1.0.1'
#pod 'AppticsCrossPromotion', '1.0.1'
#pod 'AppticsApiTracker', '1.0.1'
#pod 'AppticsInAppUpdate', '1.0.1'
#pod 'AppticsRateUs', '1.0.1'

  # Pods for AppticsDemo
  script_phase :name => 'Apptics pre build', :script => 'sh "./Pods/Apptics/scripts/regappversion" --target-name="AppticsDemo"', :execution_position => :before_compile
  script_phase :name => 'Apptics post build', :script => 'bash "./Pods/Apptics/scripts/run" --upload-symbols=false --release-configurations="Release"', :execution_position => :after_compile
  
  target 'AppticsDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppticsDemoUITests' do
    # Pods for testing
  end
  
end

target 'AppticsWidgetExtension' do
  use_frameworks!
#  pod 'Apptics-SDK', '1.0.3-debug2'
#  pod 'Apptics-SDK/EventTracker', '1.0.3-debug2'
#  pod 'Apptics-SDK/ScreenTracker', '1.0.3-debug2'
#  pod 'Apptics-SDK/CrashKit', '1.0.3-debug2'
#  pod 'Apptics-SDK/FeedbackKit', '1.0.3-debug2'
#  pod 'Apptics-Swift', '1.0.3-debug1'
  #pod 'Apptics-Swift/CrossPromotion', '1.0.3-debug1'
end
