# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

apptics_version = '1.0.7' #debug version
source_url = 'https://github.com/zoho/Apptics.git' #build source url.

#apptics_version = '1.0.7' #use non debug version for your Release build.
#source_url = 'https://github.com/CocoaPods/Specs.git' #build source url.

source 'https://github.com/CocoaPods/Specs.git'

target 'AppticsDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

# Pods for Apptics, either one is required based on your requirement.

#pod 'AppticsAnalytics/Apptics', apptics_version , :source => source_url
#pod 'AppticsAnalytics/KSCrash', apptics_version , :source => source_url

## Apptics for Objc
pod 'Apptics-Swift/Extension', apptics_version , :source => source_url
# Apptics-SDK for Objc
pod 'Apptics-SDK', apptics_version , :source => source_url
# Apptics for Swift
pod 'Apptics-Swift', apptics_version , :source => source_url
# Apptics Feedback Kit
pod 'AppticsFeedbackKit', apptics_version , :source => source_url
## Apptics In-App Update
pod 'AppticsInAppUpdate', apptics_version , :source => source_url
## Apptics Rate us
pod 'AppticsRateUs', apptics_version , :source => source_url
## Apptics RemoteConfig
pod 'AppticsRemoteConfig', apptics_version , :source => source_url
## Apptics Api Tracker
pod 'AppticsApiTracker', apptics_version , :source => source_url
## Apptics Cross Promotion
pod 'AppticsCrossPromotion', apptics_version , :source => source_url

  script_phase :name => 'Apptics pre build', :script => 'sh "./Pods/Apptics-SDK/scripts/run" --upload-symbols-for-configurations="Release, AppStore"', :execution_position => :before_compile
#script_phase :name => 'Apptics pre build', :script => 'sh "${BUILD_DIR%Build/*}SourcePackages/checkouts/Apptics-SP/scripts/run" --upload-symbols-for-configurations="Release, Appstore" "', :execution_position => :before_compile
  
  target 'AppticsDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppticsDemoUITests' do
    # Pods for testing
  end
  
end

#target 'AppticsWidgetExtension' do
#  use_frameworks!
#end
